name: timer
version: 1.0.0+1
description: A new Flutter module project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  
  flutter: 
    sdk: flutter
  sticky_headers: ^0.3.0+2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  hive: ^2.2.3
  persistent_bottom_nav_bar:
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.6.2
  dartx: ^1.1.0
  neon_widgets: ^0.1.2
  
    
dependency_overrides:
  collection: ^1.17.0
  persistent_bottom_nav_bar:
    path: ./persistent_bottom_nav_bar-5.0.2/

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Rubik
      fonts: 
      - asset: assets/fonts/Rubik-Black.ttf
      - asset: assets/fonts/Rubik-BlackItalic.ttf
      - asset: assets/fonts/Rubik-Bold.ttf
      - asset: assets/fonts/Rubik-BoldItalic.ttf
      - asset: assets/fonts/Rubik-ExtraBold.ttf
      - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
      - asset: assets/fonts/Rubik-Italic.ttf
      - asset: assets/fonts/Rubik-Light.ttf
      - asset: assets/fonts/Rubik-LightItalic.ttf
      - asset: assets/fonts/Rubik-Medium.ttf
      - asset: assets/fonts/Rubik-MediumItalic.ttf
      - asset: assets/fonts/Rubik-Regular.ttf
      - asset: assets/fonts/Rubik-SemiBold.ttf
      - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
        
        

  module: 
    androidPackage: com.example.timer
    iosBundleIdentifier: com.example.timer
    androidX: true
  uses-material-design: true

