name: timer
version: 1.0.0+1
description: A new Flutter module project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  
  flutter: 
    sdk: flutter
    
dependency_overrides:
  collection: ^1.17.0
  persistent_bottom_nav_bar:
    path: ./persistent_bottom_nav_bar-5.0.2/

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  module: 
    androidPackage: com.example.timer
    iosBundleIdentifier: com.example.timer
    androidX: true
  uses-material-design: true

